apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/home"
        backend:
          service:
            name: my-service
            port:
              number: 80
      - pathType: Prefix
        path: "/about"
        backend:
          service:
            name: my-service
            port:
              number: 80
      - pathType: Prefix
        path: "/courses"
        backend:
          service:
            name: my-service
            port:
              number: 80
      - pathType: Prefix
        path: "/contact"
        backend:
          service:
            name: my-service
            port:
              number: 80