pipeline {
    agent {
        docker { image 'python:3.9-alpine' }
    }
    stages {
        stage('Clone Repository') {
            steps {
                // Clone the specific folder from the GitHub repository
                git branch: 'main', url: 'https://github.com/developer-aayu/DevOps-Projects.git'
            }
        }
        stage('Run Script') {
            steps {
                dir('jenkins') {
                    // Run your Python script
                    sh 'python helloworld.py'
                }
            }
        }
    }
}
